In [3]:
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np
from pygame import mixer

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model(r'C:\Users\Muhammad\Desktop\PFE\Code\Model.keras')

mixer.init()
sound= mixer.Sound(r'C:\Users\Muhammad\Desktop\PFE\Code\alarm.wav')
cap = cv2.VideoCapture(0)
Score = 0
while True:
    ret, frame = cap.read()
    height,width = frame.shape[0:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)
    
    cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:
#         cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=3 )
        
       
        eye= frame[ey:ey+eh,ex:ex+ew]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
       
        prediction = model.predict(eye)
        print(prediction)
        
       
        if prediction[0][1]>0.60:
            cv2.putText(frame,'closed',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>15):
                try:
                    sound.play()
                except:
                    pass
            
        
        elif prediction[0][0]>0.60:
            cv2.putText(frame,'open',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)      
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score = Score-1
            if (Score<0):
                Score=0
            
        
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

1/1 [==============================] - 2s 2s/step
[[0.99689    0.00311006]]
1/1 [==============================] - 0s 41ms/step
[[0.9984101  0.00158984]]
1/1 [==============================] - 0s 48ms/step
[[0.98010033 0.01989971]]
1/1 [==============================] - 0s 50ms/step
[[0.73496103 0.26503897]]
1/1 [==============================] - 0s 43ms/step
[[0.2429502  0.75704986]]
1/1 [==============================] - 0s 41ms/step
[[9.9997520e-01 2.4793904e-05]]
1/1 [==============================] - 0s 40ms/step
[[0.67523456 0.32476535]]
1/1 [==============================] - 0s 40ms/step
[[9.9991345e-01 8.6480337e-05]]
1/1 [==============================] - 0s 44ms/step
[[9.9904436e-01 9.5565041e-04]]
1/1 [==============================] - 0s 40ms/step
[[0.42825794 0.571742  ]]
1/1 [==============================] - 0s 42ms/step
[[0.8211263  0.17887372]]
1/1 [==============================] - 0s 44ms/step
[[9.9988735e-01 1.1268439e-04]]
1/1 [==============================] - 0s 

1/1 [==============================] - 0s 38ms/step
[[9.9987352e-01 1.2643695e-04]]
1/1 [==============================] - 0s 41ms/step
[[9.9908710e-01 9.1295515e-04]]
1/1 [==============================] - 0s 39ms/step
[[0.9972229  0.00277708]]
1/1 [==============================] - 0s 40ms/step
[[9.994280e-01 5.719651e-04]]
1/1 [==============================] - 0s 40ms/step
[[0.9977653  0.00223474]]
1/1 [==============================] - 0s 41ms/step
[[0.0067713 0.9932287]]
1/1 [==============================] - 0s 39ms/step
[[0.04447317 0.9555268 ]]
1/1 [==============================] - 0s 40ms/step
[[0.00842289 0.99157715]]
1/1 [==============================] - 0s 40ms/step
[[0.19916292 0.80083704]]
1/1 [==============================] - 0s 41ms/step
[[0.02035542 0.97964454]]
1/1 [==============================] - 0s 42ms/step
[[0.1554813 0.8445187]]
1/1 [==============================] - 0s 39ms/step
[[0.03254592 0.96745414]]
1/1 [==============================] - 0s 41ms/step


1/1 [==============================] - 0s 40ms/step
[[0.990227   0.00977297]]
1/1 [==============================] - 0s 42ms/step
[[9.997490e-01 2.509402e-04]]
1/1 [==============================] - 0s 40ms/step
[[0.43329465 0.56670535]]
1/1 [==============================] - 0s 40ms/step
[[0.992916   0.00708402]]
1/1 [==============================] - 0s 40ms/step
[[0.7821241  0.21787594]]
1/1 [==============================] - 0s 40ms/step
[[0.964669   0.03533099]]
1/1 [==============================] - 0s 39ms/step
[[0.00199117 0.9980089 ]]
1/1 [==============================] - 0s 39ms/step
[[0.02871214 0.97128785]]
1/1 [==============================] - 0s 40ms/step
[[0.02459928 0.9754007 ]]
1/1 [==============================] - 0s 41ms/step
[[0.9161817  0.08381835]]
1/1 [==============================] - 0s 41ms/step
[[0.21578197 0.7842181 ]]
1/1 [==============================] - 0s 42ms/step
[[0.17682216 0.8231779 ]]
1/1 [==============================] - 0s 39ms/step
[[0.1054

1/1 [==============================] - 0s 41ms/step
[[0.9954882  0.00451173]]
1/1 [==============================] - 0s 41ms/step
[[0.35056934 0.6494307 ]]
1/1 [==============================] - 0s 44ms/step
[[0.9983144  0.00168561]]
1/1 [==============================] - 0s 42ms/step
[[0.99719715 0.00280286]]
1/1 [==============================] - 0s 39ms/step
[[0.99817646 0.00182358]]
1/1 [==============================] - 0s 42ms/step
[[0.8908603  0.10913968]]
1/1 [==============================] - 0s 46ms/step
[[0.978593   0.02140694]]
1/1 [==============================] - 0s 40ms/step
[[0.1493783  0.85062164]]
1/1 [==============================] - 0s 41ms/step
[[0.99676645 0.0032336 ]]
1/1 [==============================] - 0s 44ms/step
[[0.63815945 0.36184055]]
1/1 [==============================] - 0s 41ms/step
[[9.9998212e-01 1.7897974e-05]]
1/1 [==============================] - 0s 43ms/step
[[0.18274358 0.81725645]]
1/1 [==============================] - 0s 42ms/step
[[0.04